/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileContainer: typeof import('./src/components/FileContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    PdfConfigurationModal: typeof import('./src/components/PdfConfigurationModal.vue')['default']
    PdfContainerHeader: typeof import('./src/components/PdfContainerHeader.vue')['default']
    PdfFileItem: typeof import('./src/components/PdfFileItem.vue')['default']
    PdfFileList: typeof import('./src/components/PdfFileList.vue')['default']
    TestFileUploader: typeof import('./src/components/TestFileUploader.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
